/// <reference types="vitest" />
import { defineConfig, type Plugin } from 'vite'
import vue from '@vitejs/plugin-vue'
import wasm from 'vite-plugin-wasm'
import topLevelAwait from 'vite-plugin-top-level-await'
import { resolve } from 'path'

// Post-process the vite-plugin-wasm output to fix WKWebView strict-mode issue.
// vite-plugin-wasm generates:  URL = globalThis.URL
// In ES module strict mode (WKWebView/JavaScriptCore), bare assignment to an
// undeclared identifier throws ReferenceError.  Fix: declare the variable.
function wkWebViewWasmFix(): Plugin {
  return {
    name: 'wkwebview-wasm-fix',
    enforce: 'post',
    transform(code, id) {
      // Only touch the ?import wrapper generated by vite-plugin-wasm
      if (id.includes('.wasm?import') && !id.includes('&url')) {
        return code.replace(
          /^URL = globalThis\.URL$/m,
          'var URL = globalThis.URL',
        )
      }
      return null
    },
  }
}

export default defineConfig({
  plugins: [vue(), wasm(), topLevelAwait(), wkWebViewWasmFix()],
  optimizeDeps: {
    exclude: ['@tauri-apps/api', 'codemirror-lang-typst'],
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
      },
    },
  },
  build: {
    target: 'esnext',
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/test-setup.ts'],
  },
})
